# Generated by Django 4.0 on 2023-05-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_panier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panier',
            options={'ordering': ['-user']},
        ),
    ]
